### ISSUE TITLE
Remove item from watched history

### ISSUE THREAD

**Issue by Rowan-Paul** [Tracktr/tracktr-client#138]

**Comment by Rowan-Paul** [comment]
Of had je deze gesloten voor #151 @Patrickroelofs

**Comment by Patrickroelofs** [comment]
heres a little shitty design of how i imagine it works
![image](https://user-images.githubusercontent.com/7657101/201858308-762efe06-2ee6-4797-9f6c-d3acb2b59cd7.png)

**Comment by Rowan-Paul** [comment]
Looks good, pak jij die op @Patrickroelofs  anders dan doe ik dat wel na de hotfixes

**Comment by Patrickroelofs** [comment]
ik ben zo ff naar de winkel dus kijk maar
