### ISSUE TITLE
Theme color does not exist on /person crashing the page

### ISSUE THREAD

**Issue by Rowan-Paul** [Tracktr/tracktr-client#149]
The person API does not return a theme color, thus crashing the page on every person detail page.

eg.https://tracktr.app/person/18918

**Comment by Rowan-Paul** [comment]
For now I've added a ? operator so it just says undefined and does nothing

**Comment by Patrickroelofs** [comment]
deze heb je denk gefixed met je previous pr @Rowan-Paul ?
