### ISSUE TITLE
Database cannot be reached

### ISSUE THREAD

**Issue by Rowan-Paul** [Tracktr/tracktr-client#196]
I usually get this error and it only gets solved after doing `dotenv -e .env.local -- npx prisma db push`

```
The column `(not available)` does not exist in the current database. {
  message: '\n' +
    'Invalid `prisma.profile.findFirst()` invocation:\n' +
    '\n' +
    '\n' +
    'The column `(not available)` does not exist in the current database.'
```

**Comment by Rowan-Paul** [comment]
This is probably from development, when we're cleaning a table but not it's relations

**Comment by Rowan-Paul** [comment]
Perhaps a related problem: sometimes it can't connect to the database (especially seems to happen with infinite movies)

**Comment by Rowan-Paul** [comment]
Haven't had this at all this week, so might be fixed?

**Comment by Patrickroelofs** [comment]
havent seen it for a while either

**Comment by Rowan-Paul** [comment]
Then I'm closing it

**Comment by Rowan-Paul** [comment]
So last week I worked from school and didn't have it all over like 30 hours of programming. But today I'm home and had it on both my laptop & desktop so it might have something to do with my IP

**Comment by Rowan-Paul** [comment]
Haven't had this since last time - marking as closed. My current guess it's probably something about accessing the database too often which gets you rate limited
