### ISSUE TITLE
Different movie editions

### ISSUE THREAD

**Issue by Rowan-Paul** [Tracktr/tracktr-client#289]
Add the ability to watch different editions, such as a director's cut of a movie.

[TMDB does not support](https://www.themoviedb.org/talk/50cca59819c295242d091f1a) different editions, so we'll have to add it to our own using for example an optional field on Movies in our database.

**Comment by Patrickroelofs** [comment]
Lijkt me een beetje moeilijk om die data zelf te verzamelen, maar is eigenlijk ook alleen relevant voor lotr dus idk zou hier geen tijd aan besteden 😛

**Comment by Rowan-Paul** [comment]
Might be cool to add the ability to add a note to an watched item, but very low prio right now
