### ISSUE TITLE
Verslag voor School

### ISSUE THREAD

**Issue by Patrickroelofs** [Tracktr/tracktr-client#308]
**Eisen:**

- [ ] 20-25 pagina’s

**To do:**

- [x] Uitgevoerde use cases
- [x] Geplande use cases
- [x] Database schema
- [x] Code log
- [x] Verwerkte feedback
- [x] Applicatie structuur
- [x] Beschrijving experimenten
- [ ] Designs (uitleggen)
- [ ] Opmaak (affinity/indesign)

**Comment by Rowan-Paul** [comment]
Hoofdstukken volgens school:

- [ ] Voorpagina met een artist impression en pakkende titel
- [ ] Binnenzijde voorpagina: titel, studentnaam of -namen (alfabetisch geordend), studentnummers, klas, groepsnummer, docentnaam of -namen, datum, course/semestergegevens en versienummer
- [ ] Managementsamenvatting
- [ ] Inhoudsopgave
- [ ] Inleiding
- [ ] Hoofd- en deelvragen
- [ ] Aanpak, resultaten, conclusies (bij het DRP per Design Thinking fase)
- [ ] Literatuur- & bronnenlijst
- [ ] Bijlagen
- [ ] Inhoudelijke reflectie
